[log]
level = 'debug'

[proxy]
http = ''

[job]
cron = "* * * * *"
max-wait-time = '5s'
user = '29097741'
version = '3070e6c0783871cc6f72023bc91e05ea646a6005'
cookie = ''
lang = 'zh'
limit = 100
output = 'output'